[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://customdevportal.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
